[project]
name = "saree"
version = "0.1.0"
description = "Triton Python ensemble inference"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
  "numpy>=1.24",
  "opencv-python>=4.8",
  "tritonclient[http]>=2.41.0",
  "streamlit",
  "requests",
]

