# working/Cassava-Disease-Detection/configs/config.yaml

defaults:
  - model: model1
  - train: train
  - data: data    
  - _self_

model_name: "model1"
debug: true       
debug_samples: 100
run_full: false

artifacts:
  save_ckpt: false      
  save_onnx: true      

predict:
  model_path: "models/model1/model_best.ckpt"
  image_path: "data/example.jpg"
