name: Sync Subdirectory to Hugging Face
on:
  push:
    branches: [main]
    paths:
      - 'deployment/**'

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]
          cd deployment
          rm -rf .git
          git init
          git lfs install
          git lfs track "*.jpg"
          git lfs track "*.png"
          git lfs track "*.onnx"
          git lfs track "*.bin"
          git lfs track "*.pb"
          git lfs track "*.pt"
          git add .
          git commit -m "Deployment sync: $(date)"
          git push https://faranbutt789:$HF_TOKEN@huggingface.co/spaces/faranbutt789/Cassava_Leaf_Disease_Detection HEAD:main --force
